/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as PrivateImport } from './routes/_private'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as PublicForbiddenImport } from './routes/_public/forbidden'
import { Route as PrivateDashboardImport } from './routes/_private/dashboard'
import { Route as AuthRegisterImport } from './routes/_auth/register'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'
import { Route as AuthActivationAccountIndexImport } from './routes/_auth/activation-account/index'
import { Route as Oauth2ProviderCallbackImport } from './routes/oauth2.$provider.callback'
import { Route as PrivateDashboardPricingImport } from './routes/_private/dashboard/pricing'
import { Route as PrivateDashboardPaymentStatusImport } from './routes/_private/dashboard/payment-status'
import { Route as PrivateDashboardBillingImport } from './routes/_private/dashboard/billing'
import { Route as AuthActivationAccountTokenImport } from './routes/_auth/activation-account/$token'
import { Route as PrivateDashboardResignationLetterIndexImport } from './routes/_private/dashboard/resignation-letter/index'
import { Route as PrivateDashboardCvsIndexImport } from './routes/_private/dashboard/cvs/index'
import { Route as PrivateDashboardCoverLetterIndexImport } from './routes/_private/dashboard/cover-letter/index'
import { Route as PrivateDashboardAccountIndexImport } from './routes/_private/dashboard/account/index'
import { Route as PrivateDashboardCvsCvIdImport } from './routes/_private/dashboard/cvs/$cvId'
import { Route as PrivateDashboardCvsCvIdSummaryIndexImport } from './routes/_private/dashboard/cvs/$cvId/summary/index'
import { Route as PrivateDashboardCvsCvIdSkillsIndexImport } from './routes/_private/dashboard/cvs/$cvId/skills/index'
import { Route as PrivateDashboardCvsCvIdProjectIndexImport } from './routes/_private/dashboard/cvs/$cvId/project/index'
import { Route as PrivateDashboardCvsCvIdPreviewIndexImport } from './routes/_private/dashboard/cvs/$cvId/preview/index'
import { Route as PrivateDashboardCvsCvIdExperienceIndexImport } from './routes/_private/dashboard/cvs/$cvId/experience/index'
import { Route as PrivateDashboardCvsCvIdEducationIndexImport } from './routes/_private/dashboard/cvs/$cvId/education/index'
import { Route as PrivateDashboardCvsCvIdContactIndexImport } from './routes/_private/dashboard/cvs/$cvId/contact/index'
import { Route as PrivateDashboardCvsCvIdCertificationsIndexImport } from './routes/_private/dashboard/cvs/$cvId/certifications/index'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicForbiddenRoute = PublicForbiddenImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => PublicRoute,
} as any)

const PrivateDashboardRoute = PrivateDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthActivationAccountIndexRoute = AuthActivationAccountIndexImport.update(
  {
    id: '/activation-account/',
    path: '/activation-account/',
    getParentRoute: () => AuthRoute,
  } as any,
)

const Oauth2ProviderCallbackRoute = Oauth2ProviderCallbackImport.update({
  id: '/oauth2/$provider/callback',
  path: '/oauth2/$provider/callback',
  getParentRoute: () => rootRoute,
} as any)

const PrivateDashboardPricingRoute = PrivateDashboardPricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PrivateDashboardRoute,
} as any)

const PrivateDashboardPaymentStatusRoute =
  PrivateDashboardPaymentStatusImport.update({
    id: '/payment-status',
    path: '/payment-status',
    getParentRoute: () => PrivateDashboardRoute,
  } as any)

const PrivateDashboardBillingRoute = PrivateDashboardBillingImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PrivateDashboardRoute,
} as any)

const AuthActivationAccountTokenRoute = AuthActivationAccountTokenImport.update(
  {
    id: '/activation-account/$token',
    path: '/activation-account/$token',
    getParentRoute: () => AuthRoute,
  } as any,
)

const PrivateDashboardResignationLetterIndexRoute =
  PrivateDashboardResignationLetterIndexImport.update({
    id: '/resignation-letter/',
    path: '/resignation-letter/',
    getParentRoute: () => PrivateDashboardRoute,
  } as any)

const PrivateDashboardCvsIndexRoute = PrivateDashboardCvsIndexImport.update({
  id: '/cvs/',
  path: '/cvs/',
  getParentRoute: () => PrivateDashboardRoute,
} as any)

const PrivateDashboardCoverLetterIndexRoute =
  PrivateDashboardCoverLetterIndexImport.update({
    id: '/cover-letter/',
    path: '/cover-letter/',
    getParentRoute: () => PrivateDashboardRoute,
  } as any)

const PrivateDashboardAccountIndexRoute =
  PrivateDashboardAccountIndexImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => PrivateDashboardRoute,
  } as any)

const PrivateDashboardCvsCvIdRoute = PrivateDashboardCvsCvIdImport.update({
  id: '/cvs/$cvId',
  path: '/cvs/$cvId',
  getParentRoute: () => PrivateDashboardRoute,
} as any)

const PrivateDashboardCvsCvIdSummaryIndexRoute =
  PrivateDashboardCvsCvIdSummaryIndexImport.update({
    id: '/summary/',
    path: '/summary/',
    getParentRoute: () => PrivateDashboardCvsCvIdRoute,
  } as any)

const PrivateDashboardCvsCvIdSkillsIndexRoute =
  PrivateDashboardCvsCvIdSkillsIndexImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => PrivateDashboardCvsCvIdRoute,
  } as any)

const PrivateDashboardCvsCvIdProjectIndexRoute =
  PrivateDashboardCvsCvIdProjectIndexImport.update({
    id: '/project/',
    path: '/project/',
    getParentRoute: () => PrivateDashboardCvsCvIdRoute,
  } as any)

const PrivateDashboardCvsCvIdPreviewIndexRoute =
  PrivateDashboardCvsCvIdPreviewIndexImport.update({
    id: '/preview/',
    path: '/preview/',
    getParentRoute: () => PrivateDashboardCvsCvIdRoute,
  } as any)

const PrivateDashboardCvsCvIdExperienceIndexRoute =
  PrivateDashboardCvsCvIdExperienceIndexImport.update({
    id: '/experience/',
    path: '/experience/',
    getParentRoute: () => PrivateDashboardCvsCvIdRoute,
  } as any)

const PrivateDashboardCvsCvIdEducationIndexRoute =
  PrivateDashboardCvsCvIdEducationIndexImport.update({
    id: '/education/',
    path: '/education/',
    getParentRoute: () => PrivateDashboardCvsCvIdRoute,
  } as any)

const PrivateDashboardCvsCvIdContactIndexRoute =
  PrivateDashboardCvsCvIdContactIndexImport.update({
    id: '/contact/',
    path: '/contact/',
    getParentRoute: () => PrivateDashboardCvsCvIdRoute,
  } as any)

const PrivateDashboardCvsCvIdCertificationsIndexRoute =
  PrivateDashboardCvsCvIdCertificationsIndexImport.update({
    id: '/certifications/',
    path: '/certifications/',
    getParentRoute: () => PrivateDashboardCvsCvIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardImport
      parentRoute: typeof PrivateImport
    }
    '/_public/forbidden': {
      id: '/_public/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof PublicForbiddenImport
      parentRoute: typeof PublicImport
    }
    '/_auth/activation-account/$token': {
      id: '/_auth/activation-account/$token'
      path: '/activation-account/$token'
      fullPath: '/activation-account/$token'
      preLoaderRoute: typeof AuthActivationAccountTokenImport
      parentRoute: typeof AuthImport
    }
    '/_private/dashboard/billing': {
      id: '/_private/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof PrivateDashboardBillingImport
      parentRoute: typeof PrivateDashboardImport
    }
    '/_private/dashboard/payment-status': {
      id: '/_private/dashboard/payment-status'
      path: '/payment-status'
      fullPath: '/dashboard/payment-status'
      preLoaderRoute: typeof PrivateDashboardPaymentStatusImport
      parentRoute: typeof PrivateDashboardImport
    }
    '/_private/dashboard/pricing': {
      id: '/_private/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof PrivateDashboardPricingImport
      parentRoute: typeof PrivateDashboardImport
    }
    '/oauth2/$provider/callback': {
      id: '/oauth2/$provider/callback'
      path: '/oauth2/$provider/callback'
      fullPath: '/oauth2/$provider/callback'
      preLoaderRoute: typeof Oauth2ProviderCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_auth/activation-account/': {
      id: '/_auth/activation-account/'
      path: '/activation-account'
      fullPath: '/activation-account'
      preLoaderRoute: typeof AuthActivationAccountIndexImport
      parentRoute: typeof AuthImport
    }
    '/_private/dashboard/cvs/$cvId': {
      id: '/_private/dashboard/cvs/$cvId'
      path: '/cvs/$cvId'
      fullPath: '/dashboard/cvs/$cvId'
      preLoaderRoute: typeof PrivateDashboardCvsCvIdImport
      parentRoute: typeof PrivateDashboardImport
    }
    '/_private/dashboard/account/': {
      id: '/_private/dashboard/account/'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof PrivateDashboardAccountIndexImport
      parentRoute: typeof PrivateDashboardImport
    }
    '/_private/dashboard/cover-letter/': {
      id: '/_private/dashboard/cover-letter/'
      path: '/cover-letter'
      fullPath: '/dashboard/cover-letter'
      preLoaderRoute: typeof PrivateDashboardCoverLetterIndexImport
      parentRoute: typeof PrivateDashboardImport
    }
    '/_private/dashboard/cvs/': {
      id: '/_private/dashboard/cvs/'
      path: '/cvs'
      fullPath: '/dashboard/cvs'
      preLoaderRoute: typeof PrivateDashboardCvsIndexImport
      parentRoute: typeof PrivateDashboardImport
    }
    '/_private/dashboard/resignation-letter/': {
      id: '/_private/dashboard/resignation-letter/'
      path: '/resignation-letter'
      fullPath: '/dashboard/resignation-letter'
      preLoaderRoute: typeof PrivateDashboardResignationLetterIndexImport
      parentRoute: typeof PrivateDashboardImport
    }
    '/_private/dashboard/cvs/$cvId/certifications/': {
      id: '/_private/dashboard/cvs/$cvId/certifications/'
      path: '/certifications'
      fullPath: '/dashboard/cvs/$cvId/certifications'
      preLoaderRoute: typeof PrivateDashboardCvsCvIdCertificationsIndexImport
      parentRoute: typeof PrivateDashboardCvsCvIdImport
    }
    '/_private/dashboard/cvs/$cvId/contact/': {
      id: '/_private/dashboard/cvs/$cvId/contact/'
      path: '/contact'
      fullPath: '/dashboard/cvs/$cvId/contact'
      preLoaderRoute: typeof PrivateDashboardCvsCvIdContactIndexImport
      parentRoute: typeof PrivateDashboardCvsCvIdImport
    }
    '/_private/dashboard/cvs/$cvId/education/': {
      id: '/_private/dashboard/cvs/$cvId/education/'
      path: '/education'
      fullPath: '/dashboard/cvs/$cvId/education'
      preLoaderRoute: typeof PrivateDashboardCvsCvIdEducationIndexImport
      parentRoute: typeof PrivateDashboardCvsCvIdImport
    }
    '/_private/dashboard/cvs/$cvId/experience/': {
      id: '/_private/dashboard/cvs/$cvId/experience/'
      path: '/experience'
      fullPath: '/dashboard/cvs/$cvId/experience'
      preLoaderRoute: typeof PrivateDashboardCvsCvIdExperienceIndexImport
      parentRoute: typeof PrivateDashboardCvsCvIdImport
    }
    '/_private/dashboard/cvs/$cvId/preview/': {
      id: '/_private/dashboard/cvs/$cvId/preview/'
      path: '/preview'
      fullPath: '/dashboard/cvs/$cvId/preview'
      preLoaderRoute: typeof PrivateDashboardCvsCvIdPreviewIndexImport
      parentRoute: typeof PrivateDashboardCvsCvIdImport
    }
    '/_private/dashboard/cvs/$cvId/project/': {
      id: '/_private/dashboard/cvs/$cvId/project/'
      path: '/project'
      fullPath: '/dashboard/cvs/$cvId/project'
      preLoaderRoute: typeof PrivateDashboardCvsCvIdProjectIndexImport
      parentRoute: typeof PrivateDashboardCvsCvIdImport
    }
    '/_private/dashboard/cvs/$cvId/skills/': {
      id: '/_private/dashboard/cvs/$cvId/skills/'
      path: '/skills'
      fullPath: '/dashboard/cvs/$cvId/skills'
      preLoaderRoute: typeof PrivateDashboardCvsCvIdSkillsIndexImport
      parentRoute: typeof PrivateDashboardCvsCvIdImport
    }
    '/_private/dashboard/cvs/$cvId/summary/': {
      id: '/_private/dashboard/cvs/$cvId/summary/'
      path: '/summary'
      fullPath: '/dashboard/cvs/$cvId/summary'
      preLoaderRoute: typeof PrivateDashboardCvsCvIdSummaryIndexImport
      parentRoute: typeof PrivateDashboardCvsCvIdImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthActivationAccountTokenRoute: typeof AuthActivationAccountTokenRoute
  AuthActivationAccountIndexRoute: typeof AuthActivationAccountIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthActivationAccountTokenRoute: AuthActivationAccountTokenRoute,
  AuthActivationAccountIndexRoute: AuthActivationAccountIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PrivateDashboardCvsCvIdRouteChildren {
  PrivateDashboardCvsCvIdCertificationsIndexRoute: typeof PrivateDashboardCvsCvIdCertificationsIndexRoute
  PrivateDashboardCvsCvIdContactIndexRoute: typeof PrivateDashboardCvsCvIdContactIndexRoute
  PrivateDashboardCvsCvIdEducationIndexRoute: typeof PrivateDashboardCvsCvIdEducationIndexRoute
  PrivateDashboardCvsCvIdExperienceIndexRoute: typeof PrivateDashboardCvsCvIdExperienceIndexRoute
  PrivateDashboardCvsCvIdPreviewIndexRoute: typeof PrivateDashboardCvsCvIdPreviewIndexRoute
  PrivateDashboardCvsCvIdProjectIndexRoute: typeof PrivateDashboardCvsCvIdProjectIndexRoute
  PrivateDashboardCvsCvIdSkillsIndexRoute: typeof PrivateDashboardCvsCvIdSkillsIndexRoute
  PrivateDashboardCvsCvIdSummaryIndexRoute: typeof PrivateDashboardCvsCvIdSummaryIndexRoute
}

const PrivateDashboardCvsCvIdRouteChildren: PrivateDashboardCvsCvIdRouteChildren =
  {
    PrivateDashboardCvsCvIdCertificationsIndexRoute:
      PrivateDashboardCvsCvIdCertificationsIndexRoute,
    PrivateDashboardCvsCvIdContactIndexRoute:
      PrivateDashboardCvsCvIdContactIndexRoute,
    PrivateDashboardCvsCvIdEducationIndexRoute:
      PrivateDashboardCvsCvIdEducationIndexRoute,
    PrivateDashboardCvsCvIdExperienceIndexRoute:
      PrivateDashboardCvsCvIdExperienceIndexRoute,
    PrivateDashboardCvsCvIdPreviewIndexRoute:
      PrivateDashboardCvsCvIdPreviewIndexRoute,
    PrivateDashboardCvsCvIdProjectIndexRoute:
      PrivateDashboardCvsCvIdProjectIndexRoute,
    PrivateDashboardCvsCvIdSkillsIndexRoute:
      PrivateDashboardCvsCvIdSkillsIndexRoute,
    PrivateDashboardCvsCvIdSummaryIndexRoute:
      PrivateDashboardCvsCvIdSummaryIndexRoute,
  }

const PrivateDashboardCvsCvIdRouteWithChildren =
  PrivateDashboardCvsCvIdRoute._addFileChildren(
    PrivateDashboardCvsCvIdRouteChildren,
  )

interface PrivateDashboardRouteChildren {
  PrivateDashboardBillingRoute: typeof PrivateDashboardBillingRoute
  PrivateDashboardPaymentStatusRoute: typeof PrivateDashboardPaymentStatusRoute
  PrivateDashboardPricingRoute: typeof PrivateDashboardPricingRoute
  PrivateDashboardCvsCvIdRoute: typeof PrivateDashboardCvsCvIdRouteWithChildren
  PrivateDashboardAccountIndexRoute: typeof PrivateDashboardAccountIndexRoute
  PrivateDashboardCoverLetterIndexRoute: typeof PrivateDashboardCoverLetterIndexRoute
  PrivateDashboardCvsIndexRoute: typeof PrivateDashboardCvsIndexRoute
  PrivateDashboardResignationLetterIndexRoute: typeof PrivateDashboardResignationLetterIndexRoute
}

const PrivateDashboardRouteChildren: PrivateDashboardRouteChildren = {
  PrivateDashboardBillingRoute: PrivateDashboardBillingRoute,
  PrivateDashboardPaymentStatusRoute: PrivateDashboardPaymentStatusRoute,
  PrivateDashboardPricingRoute: PrivateDashboardPricingRoute,
  PrivateDashboardCvsCvIdRoute: PrivateDashboardCvsCvIdRouteWithChildren,
  PrivateDashboardAccountIndexRoute: PrivateDashboardAccountIndexRoute,
  PrivateDashboardCoverLetterIndexRoute: PrivateDashboardCoverLetterIndexRoute,
  PrivateDashboardCvsIndexRoute: PrivateDashboardCvsIndexRoute,
  PrivateDashboardResignationLetterIndexRoute:
    PrivateDashboardResignationLetterIndexRoute,
}

const PrivateDashboardRouteWithChildren =
  PrivateDashboardRoute._addFileChildren(PrivateDashboardRouteChildren)

interface PrivateRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRouteWithChildren
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRouteWithChildren,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicForbiddenRoute: typeof PublicForbiddenRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForbiddenRoute: PublicForbiddenRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PublicRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof PrivateDashboardRouteWithChildren
  '/forbidden': typeof PublicForbiddenRoute
  '/activation-account/$token': typeof AuthActivationAccountTokenRoute
  '/dashboard/billing': typeof PrivateDashboardBillingRoute
  '/dashboard/payment-status': typeof PrivateDashboardPaymentStatusRoute
  '/dashboard/pricing': typeof PrivateDashboardPricingRoute
  '/oauth2/$provider/callback': typeof Oauth2ProviderCallbackRoute
  '/activation-account': typeof AuthActivationAccountIndexRoute
  '/dashboard/cvs/$cvId': typeof PrivateDashboardCvsCvIdRouteWithChildren
  '/dashboard/account': typeof PrivateDashboardAccountIndexRoute
  '/dashboard/cover-letter': typeof PrivateDashboardCoverLetterIndexRoute
  '/dashboard/cvs': typeof PrivateDashboardCvsIndexRoute
  '/dashboard/resignation-letter': typeof PrivateDashboardResignationLetterIndexRoute
  '/dashboard/cvs/$cvId/certifications': typeof PrivateDashboardCvsCvIdCertificationsIndexRoute
  '/dashboard/cvs/$cvId/contact': typeof PrivateDashboardCvsCvIdContactIndexRoute
  '/dashboard/cvs/$cvId/education': typeof PrivateDashboardCvsCvIdEducationIndexRoute
  '/dashboard/cvs/$cvId/experience': typeof PrivateDashboardCvsCvIdExperienceIndexRoute
  '/dashboard/cvs/$cvId/preview': typeof PrivateDashboardCvsCvIdPreviewIndexRoute
  '/dashboard/cvs/$cvId/project': typeof PrivateDashboardCvsCvIdProjectIndexRoute
  '/dashboard/cvs/$cvId/skills': typeof PrivateDashboardCvsCvIdSkillsIndexRoute
  '/dashboard/cvs/$cvId/summary': typeof PrivateDashboardCvsCvIdSummaryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PublicRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof PrivateDashboardRouteWithChildren
  '/forbidden': typeof PublicForbiddenRoute
  '/activation-account/$token': typeof AuthActivationAccountTokenRoute
  '/dashboard/billing': typeof PrivateDashboardBillingRoute
  '/dashboard/payment-status': typeof PrivateDashboardPaymentStatusRoute
  '/dashboard/pricing': typeof PrivateDashboardPricingRoute
  '/oauth2/$provider/callback': typeof Oauth2ProviderCallbackRoute
  '/activation-account': typeof AuthActivationAccountIndexRoute
  '/dashboard/cvs/$cvId': typeof PrivateDashboardCvsCvIdRouteWithChildren
  '/dashboard/account': typeof PrivateDashboardAccountIndexRoute
  '/dashboard/cover-letter': typeof PrivateDashboardCoverLetterIndexRoute
  '/dashboard/cvs': typeof PrivateDashboardCvsIndexRoute
  '/dashboard/resignation-letter': typeof PrivateDashboardResignationLetterIndexRoute
  '/dashboard/cvs/$cvId/certifications': typeof PrivateDashboardCvsCvIdCertificationsIndexRoute
  '/dashboard/cvs/$cvId/contact': typeof PrivateDashboardCvsCvIdContactIndexRoute
  '/dashboard/cvs/$cvId/education': typeof PrivateDashboardCvsCvIdEducationIndexRoute
  '/dashboard/cvs/$cvId/experience': typeof PrivateDashboardCvsCvIdExperienceIndexRoute
  '/dashboard/cvs/$cvId/preview': typeof PrivateDashboardCvsCvIdPreviewIndexRoute
  '/dashboard/cvs/$cvId/project': typeof PrivateDashboardCvsCvIdProjectIndexRoute
  '/dashboard/cvs/$cvId/skills': typeof PrivateDashboardCvsCvIdSkillsIndexRoute
  '/dashboard/cvs/$cvId/summary': typeof PrivateDashboardCvsCvIdSummaryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_private/dashboard': typeof PrivateDashboardRouteWithChildren
  '/_public/forbidden': typeof PublicForbiddenRoute
  '/_auth/activation-account/$token': typeof AuthActivationAccountTokenRoute
  '/_private/dashboard/billing': typeof PrivateDashboardBillingRoute
  '/_private/dashboard/payment-status': typeof PrivateDashboardPaymentStatusRoute
  '/_private/dashboard/pricing': typeof PrivateDashboardPricingRoute
  '/oauth2/$provider/callback': typeof Oauth2ProviderCallbackRoute
  '/_auth/activation-account/': typeof AuthActivationAccountIndexRoute
  '/_private/dashboard/cvs/$cvId': typeof PrivateDashboardCvsCvIdRouteWithChildren
  '/_private/dashboard/account/': typeof PrivateDashboardAccountIndexRoute
  '/_private/dashboard/cover-letter/': typeof PrivateDashboardCoverLetterIndexRoute
  '/_private/dashboard/cvs/': typeof PrivateDashboardCvsIndexRoute
  '/_private/dashboard/resignation-letter/': typeof PrivateDashboardResignationLetterIndexRoute
  '/_private/dashboard/cvs/$cvId/certifications/': typeof PrivateDashboardCvsCvIdCertificationsIndexRoute
  '/_private/dashboard/cvs/$cvId/contact/': typeof PrivateDashboardCvsCvIdContactIndexRoute
  '/_private/dashboard/cvs/$cvId/education/': typeof PrivateDashboardCvsCvIdEducationIndexRoute
  '/_private/dashboard/cvs/$cvId/experience/': typeof PrivateDashboardCvsCvIdExperienceIndexRoute
  '/_private/dashboard/cvs/$cvId/preview/': typeof PrivateDashboardCvsCvIdPreviewIndexRoute
  '/_private/dashboard/cvs/$cvId/project/': typeof PrivateDashboardCvsCvIdProjectIndexRoute
  '/_private/dashboard/cvs/$cvId/skills/': typeof PrivateDashboardCvsCvIdSkillsIndexRoute
  '/_private/dashboard/cvs/$cvId/summary/': typeof PrivateDashboardCvsCvIdSummaryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/forbidden'
    | '/activation-account/$token'
    | '/dashboard/billing'
    | '/dashboard/payment-status'
    | '/dashboard/pricing'
    | '/oauth2/$provider/callback'
    | '/activation-account'
    | '/dashboard/cvs/$cvId'
    | '/dashboard/account'
    | '/dashboard/cover-letter'
    | '/dashboard/cvs'
    | '/dashboard/resignation-letter'
    | '/dashboard/cvs/$cvId/certifications'
    | '/dashboard/cvs/$cvId/contact'
    | '/dashboard/cvs/$cvId/education'
    | '/dashboard/cvs/$cvId/experience'
    | '/dashboard/cvs/$cvId/preview'
    | '/dashboard/cvs/$cvId/project'
    | '/dashboard/cvs/$cvId/skills'
    | '/dashboard/cvs/$cvId/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/forbidden'
    | '/activation-account/$token'
    | '/dashboard/billing'
    | '/dashboard/payment-status'
    | '/dashboard/pricing'
    | '/oauth2/$provider/callback'
    | '/activation-account'
    | '/dashboard/cvs/$cvId'
    | '/dashboard/account'
    | '/dashboard/cover-letter'
    | '/dashboard/cvs'
    | '/dashboard/resignation-letter'
    | '/dashboard/cvs/$cvId/certifications'
    | '/dashboard/cvs/$cvId/contact'
    | '/dashboard/cvs/$cvId/education'
    | '/dashboard/cvs/$cvId/experience'
    | '/dashboard/cvs/$cvId/preview'
    | '/dashboard/cvs/$cvId/project'
    | '/dashboard/cvs/$cvId/skills'
    | '/dashboard/cvs/$cvId/summary'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_private'
    | '/_public'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_private/dashboard'
    | '/_public/forbidden'
    | '/_auth/activation-account/$token'
    | '/_private/dashboard/billing'
    | '/_private/dashboard/payment-status'
    | '/_private/dashboard/pricing'
    | '/oauth2/$provider/callback'
    | '/_auth/activation-account/'
    | '/_private/dashboard/cvs/$cvId'
    | '/_private/dashboard/account/'
    | '/_private/dashboard/cover-letter/'
    | '/_private/dashboard/cvs/'
    | '/_private/dashboard/resignation-letter/'
    | '/_private/dashboard/cvs/$cvId/certifications/'
    | '/_private/dashboard/cvs/$cvId/contact/'
    | '/_private/dashboard/cvs/$cvId/education/'
    | '/_private/dashboard/cvs/$cvId/experience/'
    | '/_private/dashboard/cvs/$cvId/preview/'
    | '/_private/dashboard/cvs/$cvId/project/'
    | '/_private/dashboard/cvs/$cvId/skills/'
    | '/_private/dashboard/cvs/$cvId/summary/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  Oauth2ProviderCallbackRoute: typeof Oauth2ProviderCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  Oauth2ProviderCallbackRoute: Oauth2ProviderCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_private",
        "/_public",
        "/oauth2/$provider/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/forgot-password",
        "/_auth/login",
        "/_auth/register",
        "/_auth/activation-account/$token",
        "/_auth/activation-account/"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/dashboard"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/forbidden"
      ]
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx",
      "parent": "/_auth"
    },
    "/_private/dashboard": {
      "filePath": "_private/dashboard.tsx",
      "parent": "/_private",
      "children": [
        "/_private/dashboard/billing",
        "/_private/dashboard/payment-status",
        "/_private/dashboard/pricing",
        "/_private/dashboard/cvs/$cvId",
        "/_private/dashboard/account/",
        "/_private/dashboard/cover-letter/",
        "/_private/dashboard/cvs/",
        "/_private/dashboard/resignation-letter/"
      ]
    },
    "/_public/forbidden": {
      "filePath": "_public/forbidden.tsx",
      "parent": "/_public"
    },
    "/_auth/activation-account/$token": {
      "filePath": "_auth/activation-account/$token.tsx",
      "parent": "/_auth"
    },
    "/_private/dashboard/billing": {
      "filePath": "_private/dashboard/billing.tsx",
      "parent": "/_private/dashboard"
    },
    "/_private/dashboard/payment-status": {
      "filePath": "_private/dashboard/payment-status.tsx",
      "parent": "/_private/dashboard"
    },
    "/_private/dashboard/pricing": {
      "filePath": "_private/dashboard/pricing.tsx",
      "parent": "/_private/dashboard"
    },
    "/oauth2/$provider/callback": {
      "filePath": "oauth2.$provider.callback.tsx"
    },
    "/_auth/activation-account/": {
      "filePath": "_auth/activation-account/index.tsx",
      "parent": "/_auth"
    },
    "/_private/dashboard/cvs/$cvId": {
      "filePath": "_private/dashboard/cvs/$cvId.tsx",
      "parent": "/_private/dashboard",
      "children": [
        "/_private/dashboard/cvs/$cvId/certifications/",
        "/_private/dashboard/cvs/$cvId/contact/",
        "/_private/dashboard/cvs/$cvId/education/",
        "/_private/dashboard/cvs/$cvId/experience/",
        "/_private/dashboard/cvs/$cvId/preview/",
        "/_private/dashboard/cvs/$cvId/project/",
        "/_private/dashboard/cvs/$cvId/skills/",
        "/_private/dashboard/cvs/$cvId/summary/"
      ]
    },
    "/_private/dashboard/account/": {
      "filePath": "_private/dashboard/account/index.tsx",
      "parent": "/_private/dashboard"
    },
    "/_private/dashboard/cover-letter/": {
      "filePath": "_private/dashboard/cover-letter/index.tsx",
      "parent": "/_private/dashboard"
    },
    "/_private/dashboard/cvs/": {
      "filePath": "_private/dashboard/cvs/index.tsx",
      "parent": "/_private/dashboard"
    },
    "/_private/dashboard/resignation-letter/": {
      "filePath": "_private/dashboard/resignation-letter/index.tsx",
      "parent": "/_private/dashboard"
    },
    "/_private/dashboard/cvs/$cvId/certifications/": {
      "filePath": "_private/dashboard/cvs/$cvId/certifications/index.tsx",
      "parent": "/_private/dashboard/cvs/$cvId"
    },
    "/_private/dashboard/cvs/$cvId/contact/": {
      "filePath": "_private/dashboard/cvs/$cvId/contact/index.tsx",
      "parent": "/_private/dashboard/cvs/$cvId"
    },
    "/_private/dashboard/cvs/$cvId/education/": {
      "filePath": "_private/dashboard/cvs/$cvId/education/index.tsx",
      "parent": "/_private/dashboard/cvs/$cvId"
    },
    "/_private/dashboard/cvs/$cvId/experience/": {
      "filePath": "_private/dashboard/cvs/$cvId/experience/index.tsx",
      "parent": "/_private/dashboard/cvs/$cvId"
    },
    "/_private/dashboard/cvs/$cvId/preview/": {
      "filePath": "_private/dashboard/cvs/$cvId/preview/index.tsx",
      "parent": "/_private/dashboard/cvs/$cvId"
    },
    "/_private/dashboard/cvs/$cvId/project/": {
      "filePath": "_private/dashboard/cvs/$cvId/project/index.tsx",
      "parent": "/_private/dashboard/cvs/$cvId"
    },
    "/_private/dashboard/cvs/$cvId/skills/": {
      "filePath": "_private/dashboard/cvs/$cvId/skills/index.tsx",
      "parent": "/_private/dashboard/cvs/$cvId"
    },
    "/_private/dashboard/cvs/$cvId/summary/": {
      "filePath": "_private/dashboard/cvs/$cvId/summary/index.tsx",
      "parent": "/_private/dashboard/cvs/$cvId"
    }
  }
}
ROUTE_MANIFEST_END */
